plugins {
    id "com.gradleup.shadow" version "9.4.2"
    id "com.matthewprenger.cursegradle"
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    mods {
        forge {
            sourceSet project(":neoforge").sourceSets.main
        }
    }
}

architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "forge"
    }
}

configurations {
    common
    forgeLike
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    implementation(project(path: ":neoforge")) { transitive false }
    common(project(path: ":common")) { transitive false }
    common(project(path: ":testmod-common")) { transitive false }
}
